[package]
authors = ["guillem.cordoba@gmail.com", "tim@pragmaticmind.com"]
edition = "2018"
name = "exercise"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "exercise"

[dependencies]
derive_more = "0"
serde = "1"

hc_utils = "0"
hdk3 = "0"
chrono = "0.4.19"