[package]
authors = ["joshuadparkin@gmail.com"]
edition = "2018"
name = "remote_call"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "remote_call"

[dependencies]
derive_more = "0"
serde = "1"
hdk = { version = "0.0.129", features = ["encoding"] }